server:
  port: 8080
  servlet:
    context-path:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  tomcat:
    uri-encoding: UTF-8
    max-connections: 1000
    max-threads: 200
    min-spare-threads: 200
    accept-count: 500

spring:
  application:
    name: elves.online
    code: 20230321
    nameCN: 精灵在线
    version: 2.0.0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    host:
    port: 6379
    password:
    database: 0
    connect-timeout: 0
    jedis:
      pool:
        # 最大连接数
        max-active: 8
        # 最大空闲
        max-idle: 8
        # 最小空闲
        min-idle: 0
        # 阻塞等待时间
        max-wait: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    druid:
      filter:
        stat:
          # 开启 sql 监控
          enabled: true
          # 慢 sql 监控
          log-slow-sql: true
          # 5 秒
          slow-sql-millis: 5000
          # 合并 sql
          merge-sql: true
        wall:
          config:
            # 允许多条 sql 同时执行
            multi-statement-allow: true
      initial-size: 5
      min-idle: 5
      max-active: 12
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 12
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filters: stat,wall

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-location: classpath*:mapper/**/*Mapper.xml